### ISSUE TITLE
sourceSet do not seem to be taken into account

### ISSUE THREAD

**Issue by osana** [vanniktech/gradle-dependency-graph-generator-plugin#41]
I am trying to generate a graph for a library that has multiple modules. See the sourceSet.
https://github.com/mapbox/mapbox-java/blob/49a07650f81c5b8982501b9bedb553c58493b44e/services/build.gradle#L3-L8

The resulting graph shows only  the dependency included under 
`dependencies`

![dependency-graph-mapbox-libraries](https://user-images.githubusercontent.com/32496536/38942846-e5c3da92-42fd-11e8-813e-12c6216e1b85.png)

cc @Guardiola31337

**Comment by vanniktech** [comment]
Yes that's right and should be working as intended. Here - https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/1c1d21d790582cb1859e2f213758b00ddb74f3f6/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt#L41 - we only listen for classpaths for debug + release. You might need to tweak it and write a custom Generator. (There's a section about this in the tutorial).

**Comment by Guardiola31337** [comment]
Hey @vanniktech :wave: thanks for the quick reply!

We're already implementing a custom generator :eyes: https://github.com/mapbox/mapbox-java/blob/aab3cdfc6c2da780548070d21626ab9d1c0730e6/gradle/dependencies-graph.gradle do you know how to tweak it so that takes into account the modules included in `sourceSets` https://github.com/mapbox/mapbox-java/blob/49a07650f81c5b8982501b9bedb553c58493b44e/services/build.gradle#L3-L8?

Thanks for developing this awesome plugin!

**Comment by vanniktech** [comment]
You do implement one but you don't tweak the configurations with the lambda function. I should have some time later to play around with it.

**Comment by Guardiola31337** [comment]
That's awesome, thanks a lot :pray:

Let us know if you have any questions or if you need further information/clarification.

**Comment by Guardiola31337** [comment]
Thanks for the detailed info @vanniktech 🙏

We're still getting the same graph as before 😥

![dependency-graph-mapbox-libraries](https://user-images.githubusercontent.com/1668582/38989548-89a36dec-43d7-11e8-9531-20c9958389a8.png)

Sorry if I didn't make myself clear. We're only interested in the library graphs (for now). The idea is to know what Mapbox dependencies include each library module and in the case of `services` we're not only depending on `services-core` and `services-geojson` (declared explicitly under `dependencies`), we're also including `services-directions`, `services-geocoding`, `services-matching`, `services-matrix`, `services-optimization`, `services-staticmap` and `services-speech` modules via `sourceSets` https://github.com/mapbox/mapbox-java/blob/49a07650f81c5b8982501b9bedb553c58493b44e/services/build.gradle#L3-L8 and those aren't drawn (taken into account) in the graph. We want those included in the graph as well because ultimately those are also dependencies included in that module but in a different way (through `sourceSets`). Does that make sense? Is there any way to customize the Generator so that those modules are also included in the dependencies graph? 

If you want to try it out yourself, you can apply this patch file on `aab3cdf`

```diff
diff --git a/Makefile b/Makefile
index 983a3d29..b1aff7b3 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,10 @@ publish-local:
     export IS_LOCAL_DEVELOPMENT=true; ./gradlew :services-turf:uploadArchives ; \
 
 graphs:
-	./gradlew generateDependencyGraphMapboxLibraries
+	./gradlew :services-core:generateDependencyGraphMapboxLibraries
+	./gradlew :services-geojson:generateDependencyGraphMapboxLibraries
+	./gradlew :services:generateDependencyGraphMapboxLibraries
+	./gradlew :services-turf:generateDependencyGraphMapboxLibraries
 
 directions-matrix-fixtures:
 	# request a symmetric 3x3 matrix for cars
diff --git a/build.gradle b/build.gradle
index d2adb891..9d934e30 100644
--- a/build.gradle
+++ b/build.gradle
@@ -68,4 +68,3 @@ task clean(type: Delete) {
 }
 
 apply from: "${rootDir}/gradle/sonarqube.gradle"
-apply from: "${rootDir}/gradle/dependencies-graph.gradle"
diff --git a/gradle/dependencies-graph.gradle b/gradle/dependencies-graph.gradle
index dc8c03eb..167683d3 100644
--- a/gradle/dependencies-graph.gradle
+++ b/gradle/dependencies-graph.gradle
@@ -1,6 +1,7 @@
 buildscript {
     repositories {
         mavenCentral()
+        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     }
 
     dependencies {
@@ -19,7 +20,6 @@ plugins.apply(DependencyGraphGeneratorPlugin)
 
 def mapboxGenerator = new Generator(
         "mapboxLibraries", // Suffix for our Gradle task.
-        "", // Root suffix that we don't want in this case.
         { dependency -> dependency.getModuleGroup().startsWith("com.mapbox.mapboxsdk") }, // Only want Mapbox libs.
         { dependency -> true }, // Include transitive dependencies.
 )
diff --git a/gradle/dependencies.gradle b/gradle/dependencies.gradle
index 6c37bf70..b97908dd 100644
--- a/gradle/dependencies.gradle
+++ b/gradle/dependencies.gradle
@@ -14,15 +14,15 @@ ext {
   ]
 
   pluginVersion = [
-      checkstyle : '8.2',
-      pmd        : '5.8.1',
-      jacoco     : '0.7.9',
-      errorprone : '0.0.13',
-      coveralls  : '2.8.1',
-      spotbugs   : '1.3',
-      sonarqube  : '2.6-rc1',
-      buildConfig: '1.1.8',
-      dependencyGraph: '0.3.0'
+      checkstyle     : '8.2',
+      pmd            : '5.8.1',
+      jacoco         : '0.7.9',
+      errorprone     : '0.0.13',
+      coveralls      : '2.8.1',
+      spotbugs       : '1.3',
+      sonarqube      : '2.6-rc1',
+      buildConfig    : '1.1.8',
+      dependencyGraph: '0.4.0-SNAPSHOT'
   ]
   dependenciesList = [
       autoValue           : "com.google.auto.value:auto-value:${version.autoValue}",
@@ -42,11 +42,11 @@ ext {
 
 
   pluginDependencies = [
-      checkstyle : "com.puppycrawl.tools:checkstyle:${pluginVersion.checkstyle}",
-      spotbugs   : "gradle.plugin.com.github.spotbugs:gradlePlugin:${pluginVersion.spotbugs}",
-      sonarqube  : "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:${pluginVersion.sonarqube}",
-      errorprone : "net.ltgt.gradle:gradle-errorprone-plugin:${pluginVersion.errorprone}",
-      buildConfig: "gradle.plugin.de.fuerstenau:BuildConfigPlugin:${pluginVersion.buildConfig}",
+      checkstyle     : "com.puppycrawl.tools:checkstyle:${pluginVersion.checkstyle}",
+      spotbugs       : "gradle.plugin.com.github.spotbugs:gradlePlugin:${pluginVersion.spotbugs}",
+      sonarqube      : "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:${pluginVersion.sonarqube}",
+      errorprone     : "net.ltgt.gradle:gradle-errorprone-plugin:${pluginVersion.errorprone}",
+      buildConfig    : "gradle.plugin.de.fuerstenau:BuildConfigPlugin:${pluginVersion.buildConfig}",
       dependencyGraph: "com.vanniktech:gradle-dependency-graph-generator-plugin:${pluginVersion.dependencyGraph}"
   ]
 }
\ No newline at end of file
```
run `$> make graphs` and 👀 the `services` graph generated.

Let us know if you have any follow up questions or if you need further information/clarification.

**Comment by vanniktech** [comment]
Oh now I'm getting what you mean. Instead of using `api` / `implementation` on the module you're referencing the source set.

Currently that's not possible. We're using the normal configuration from Gradle and then get the resolved dependencies and artifacts. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/87523ada04a0c81243e224a460c7b96ada01a06c/src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt#L45

There might be a way to hook things up and try to match the sourceset to a project. Although it will be very tricky and brittle with the possibility to break between different Gradle versions.

What's the reason behind adding the sourcesets but not the dependency?

**Comment by Guardiola31337** [comment]
> Instead of using `api` / `implementation` on the module you're referencing the source set.

Well actually we're referencing both the `dependencies` (`api` / `implementation`) and the `sourceSets`. That's why we were expecting all of them to be drawn in the graph.

> There might be a way to hook things up and try to match the sourceset to a project.

Do you know how to tweak the Generator so that takes into account the modules included in `sourceSets` plus the modules referenced in `dependencies`?

> Although it will be very tricky and brittle with the possibility to break between different Gradle versions.

Not a problem because ultimately we're maintaining that Generator. If it fails in the future we can fix it from our side. It'll be a matter of knowing how to get the modules from `sourceSets` included when using the latest Gradle version. Don't think that'll change that much.

> What's the reason behind adding the sourcesets but not the dependency?

Generating one artifact out of different Gradle modules. That's the only way we found to keep every API as a separate Gradle module, but publish them all as one artifact. We know it's hacky 😅 but it works ¯\\\_(ツ)\_/¯

**Comment by vanniktech** [comment]
> Well actually we're referencing both the dependencies (api / implementation) and the sourceSets. That's why we were expecting all of them to be drawn in the graph.

In https://github.com/mapbox/mapbox-java/blob/49a07650f81c5b8982501b9bedb553c58493b44e/services/build.gradle#L3-L8 you don't specify the dependencies of all of the services. Just core & geojson. Both of which end up in the graph.

> Do you know how to tweak the Generator so that takes into account the modules included in sourceSets plus the modules referenced in dependencies?

Nope. I'd need to dig into the Gradle API too and already getting this far took quite some time so I'd expect even worse with sourceSets.

> Not a problem because ultimately we're maintaining that Generator. If it fails in the future we can fix it from our side. It'll be a matter of knowing how to get the modules from sourceSets included when using the latest Gradle version. Don't think that'll change that much though.

True. Maybe you do find a solution for now to get some data from the configuration. I ended up debugging it and calling each method and seeing what I get in return. :man_shrugging: 

> Generating one artifact out of different Gradle modules. That's the only way we found to keep every API as a separate Gradle module, but publish them all as one artifact. We know it's hacky sweat_smile but it works ¯\_(ツ)_/¯

Interesting. There's no way to merge multiple jars into one big one?

**Comment by Guardiola31337** [comment]
> In https://github.com/mapbox/mapbox-java/blob/49a07650f81c5b8982501b9bedb553c58493b44e/services/build.gradle#L3-L8 you don't specify the dependencies of all of the services. Just core & geojson. Both of which end up in the graph.

Yeah, we know. But ultimately `sourceSets` modules are also included and we were wondering if they could be drawn in the graph as well somehow.

> Nope. I'd need to dig into the Gradle API too and already getting this far took quite some time so I'd expect even worse with sourceSets.

> True. Maybe you do find a solution for now to get some data from the configuration. I ended up debugging it and calling each method and seeing what I get in return. 🤷‍♂️

Keep us posted if you come up with any other ideas or approaches to get those modules included.

> Interesting. There's no way to merge multiple jars into one big one?

Nope as far as we know 😥 Do you know?

BTW, thanks a lot for your help and insights. We appreciate them 🙏

**Comment by vanniktech** [comment]
No I don't know anything about it. Haven't had the need to tinker around with it.
I'll think about it. Feel free to try for yourself too.

**Comment by osana** [comment]
Thank you @vanniktech and @Guardiola31337 for reviewing the code 
Hopefully, I address all issues now.

**Comment by vanniktech** [comment]
@Guardiola31337 have you come up with anything? Otherwise I'm tempted to close this as source sets are different than the actual Gradle dependencies and I can't think of an easy way to handle this correctly without any hacks.

**Comment by Guardiola31337** [comment]
@vanniktech 
> have you come up with anything?

Nope 😓

> I can't think of an easy way to handle this correctly without any hacks.

Could you share the "hacks" you're thinking of? I'd like to keep exploring a working solution for source sets.

In the meantime, feel free to close here and we'll reopen if we come up with anything.

Thanks Niklas 🙏

**Comment by vanniktech** [comment]
One way to figure this out would be to get the package name from the source set and then try to match that back to the [group](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getGroup--) that every project has - but it's a long shot.
